DATA_PATH = '/content/drive/MyDrive/SETI/input/'
DEVICE = 'cuda'
EPOCHS = 3
BATCH_SIZE = 32
TARGET_SIZE = 1

MODEL_NAME = 'nfnet_l0'
CHANNELS = 6

LEARNING_RATE = 5e-4
FACTOR = 0.1
PATIENCE = 2
EPS = 1e-8